var nome = prompt("Qual é o seu nome?") 
var sobrenome = prompt("Qual é o seu sobrenome?")
alert("Bem vinda "+nome+" "+sobrenome)
document.write("<h1>Bem-vinda "+nome+" "+sobrenome+"</h1>")
document.write("<img src=//img/img1.png>")